FROM nginx:alpine
COPY index.html /usr/share/nginx/html/
COPY teacher.html /usr/share/nginx/html/
COPY student.html /usr/share/nginx/html/
COPY nginx-student.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

